import 'dart:io';

import 'package:path/path.dart' as p;

/// Generates a unified firebase_options.dart file for the Flutter project.
///
/// After flutterfire configure runs per flavor (producing firebase_options_dev.dart,
/// firebase_options_prod.dart, etc.), this generator creates a single
/// lib/firebase_options.dart that imports all of them and exposes a
/// getFirebaseOptions(flavor) function.
///
/// Generated file example:
///   FirebaseOptions getFirebaseOptions(String flavor) {
///     switch (flavor) {
///       case 'dev': return options_dev.DefaultFirebaseOptions.currentPlatform;
///       case 'prod': return options_prod.DefaultFirebaseOptions.currentPlatform;
///       default: throw UnsupportedError('Unknown flavor: $flavor');
///     }
///   }
class FirebaseOptionsGenerator {
  /// Generates lib/firebase_options.dart in [projectRoot].
  ///
  /// [flavors]: list of flavor names that have Firebase configured.
  /// Always overwrites the existing file (idempotent).
  static void generate(
    String projectRoot,
    List<String> flavors, {
    bool dryRun = false,
  }) {
    final outputPath = p.join(projectRoot, 'lib', 'firebase_options.dart');
    final content = _buildContent(flavors);

    if (dryRun) {
      print('  · [dry-run] Would write: lib/firebase_options.dart');
      return;
    }

    File(outputPath).writeAsStringSync(content);
    print('  ✓ lib/firebase_options.dart');
  }

  static String _buildContent(List<String> flavors) {
    final sb = StringBuffer();

    sb.writeln('// Generated by easy_setup. Do not edit manually.');
    sb.writeln('// ignore_for_file: lines_longer_than_80_chars');
    sb.writeln();
    sb.writeln("import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;");
    for (final flavor in flavors) {
      sb.writeln("import 'firebase_options_$flavor.dart' as options_$flavor;");
    }
    sb.writeln();
    sb.writeln('/// Returns the [FirebaseOptions] for the given [flavor].');
    sb.writeln('FirebaseOptions getFirebaseOptions(String flavor) {');
    sb.writeln('  switch (flavor) {');
    for (final flavor in flavors) {
      sb.writeln("    case '$flavor':");
      sb.writeln('      return options_$flavor.DefaultFirebaseOptions.currentPlatform;');
    }
    sb.writeln('    default:');
    sb.writeln("      throw UnsupportedError(");
    sb.writeln("        'No Firebase options configured for flavor: \"\$flavor\".\\n'");
    sb.writeln("        'Available flavors: ${flavors.join(', ')}',");
    sb.writeln('      );');
    sb.writeln('  }');
    sb.writeln('}');

    return sb.toString();
  }
}
