// Generated by easy_setup. Do not edit manually.
// ignore_for_file: lines_longer_than_80_chars

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options_dev.dart' as options_dev;
import 'firebase_options_prod.dart' as options_prod;

/// Returns the [FirebaseOptions] for the given [flavor].
FirebaseOptions getFirebaseOptions(String flavor) {
  switch (flavor) {
    case 'dev':
      return options_dev.DefaultFirebaseOptions.currentPlatform;
    case 'prod':
      return options_prod.DefaultFirebaseOptions.currentPlatform;
    default:
      throw UnsupportedError(
        'No Firebase options configured for flavor: "$flavor".\n'
        'Available flavors: dev, prod',
      );
  }
}
