/// Sources for the screenshot tour (V2_PLAN.md §5.2, layer ①).
///
/// Two of the three files are derived — the harness protocol has to match
/// the host watcher exactly, and the driver is boilerplate — so they are
/// rewritten on every run. The tour itself is the app's own: which screens,
/// in which order, with which demo data. It is seeded once and then owned
/// by the project.
abstract final class CaptureTemplates {
  /// Marker files exchanged between the on-device tour and the host
  /// watcher, inside the app's tmp directory.
  static const requestFileName = 'shot_request.txt';
  static const doneFileName = 'shot_done.txt';

  static const harnessRelativePath =
      'integration_test/store_screenshot_harness.dart';
  static const tourRelativePath =
      'integration_test/store_screenshots_test.dart';
  static const driverRelativePath = 'test_driver/integration_test.dart';

  /// `flutter drive` needs a driver entry point; the capture itself is
  /// done by the host watcher, so there is nothing to do here.
  static String driver() => '''
// Generated by `easy_setup capture` — regenerated on every run.
import 'package:integration_test/integration_test_driver.dart';

Future<void> main() => integrationDriver();
''';

  static String harness() => '''
// Generated by `easy_setup capture` — regenerated on every run, so any
// edit here is lost. The handshake below has to stay in step with the
// host-side watcher.
//
// Why a handshake instead of `binding.takeScreenshot`: the binding reads
// back the Flutter surface, which is unreliable under Impeller/Metal —
// whole runs come back as the splash screen. The host captures through
// the simulator's compositor instead, so a shot is always exactly what is
// on screen, status bar included.
library;

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// The locale being captured, passed in by `easy_setup capture`. Use it to
/// seed locale-specific demo data.
const captureLocale =
    String.fromEnvironment('SCREENSHOT_LOCALE', defaultValue: 'en');

/// True while running under `easy_setup capture`.
const captureMode = bool.fromEnvironment('SCREENSHOT_MODE');

/// Asks the host to capture the screen, and waits until it has.
///
/// [name] becomes the file name, so it also fixes the order the stores
/// display the screenshots in — keep the `01_`, `02_` prefixes.
Future<void> shot(WidgetTester tester, String name) async {
  final dir = Directory.systemTemp.path;
  final done = File('\$dir/$doneFileName');
  if (done.existsSync()) done.deleteSync();
  // Written to a temp name and renamed, so the watcher can never read a
  // half-written request.
  File('\$dir/$requestFileName.tmp')
    ..writeAsStringSync(name)
    ..renameSync('\$dir/$requestFileName');

  final deadline = DateTime.now().add(const Duration(seconds: 60));
  while (DateTime.now().isBefore(deadline)) {
    await tester.pump(const Duration(milliseconds: 100));
    if (done.existsSync() && done.readAsStringSync().trim() == name) return;
  }
  throw StateError(
    'No capture response for "\$name". Run the tour with '
    '`easy_setup capture` — `flutter drive` on its own has no watcher to '
    'take the screenshot.',
  );
}

/// Pumps for a fixed duration.
///
/// `pumpAndSettle` never returns when the app has a looping animation, so
/// the tour waits by the clock instead.
Future<void> pumpFor(WidgetTester tester, Duration duration) async {
  final deadline = DateTime.now().add(duration);
  while (DateTime.now().isBefore(deadline)) {
    await tester.pump(const Duration(milliseconds: 50));
  }
}

/// Pumps until [finder] matches, for screens that load asynchronously.
Future<void> waitFor(
  WidgetTester tester,
  Finder finder, {
  Duration timeout = const Duration(seconds: 20),
}) async {
  final deadline = DateTime.now().add(timeout);
  while (DateTime.now().isBefore(deadline)) {
    await tester.pump(const Duration(milliseconds: 100));
    if (tester.any(finder)) return;
  }
  throw StateError('Screen never appeared: \$finder');
}
''';

  /// The tour scaffold — seeded once, then owned by the project.
  static String tour(String packageName) => '''
/// Store screenshot tour.
///
/// Run it with `easy_setup capture`, which boots the simulator, freezes
/// the status bar and captures each `shot()` from the host. Outputs land
/// in assets/store/screenshots/raw/<locale>/<device>/ and are framed into
/// store-spec PNGs by `easy_setup setup --only screenshots`.
///
/// Everything below is yours to write — see the store-screenshots skill.
library;

import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

// TODO: import your app's root widget, e.g.
// import 'package:$packageName/main.dart';

import 'store_screenshot_harness.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();
  // Let the app's animations actually run — the default policy freezes
  // them, and a frozen hero shot looks dead.
  binding.framePolicy = LiveTestWidgetsFlutterBindingFramePolicy.fullyLive;

  testWidgets('store screenshot tour', (tester) async {
    await seedDemoData();

    // TODO: pump your app's root widget, e.g.
    //   await tester.pumpWidget(const MyApp());
    //   await waitFor(tester, find.byType(HomeScreen));
    await pumpFor(tester, const Duration(seconds: 2));

    await shot(tester, '01_home');

    // TODO: navigate to the next screen and capture it. Prefer driving the
    // app's own state or Navigator directly over tapping — it is far less
    // brittle than hunting for widgets.
    //
    //   final nav = tester.state<NavigatorState>(find.byType(Navigator));
    //   nav.push(MaterialPageRoute<void>(builder: (_) => const Detail()));
    //   await pumpFor(tester, const Duration(milliseconds: 1200));
    //   await shot(tester, '02_detail');
  });
}

/// Fills the app with the content the screenshots should show.
///
/// An empty app makes for empty screenshots. Seed straight into whatever
/// the app reads at startup (SharedPreferences, a local database, a fake
/// API client) — before the widget is pumped, so the first frame is
/// already populated. Keep the data plausible: real sentences, realistic
/// dates, enough rows that lists and charts look alive.
Future<void> seedDemoData() async {
  // TODO
}
''';
}
