import 'dart:io';

import 'package:path/path.dart' as p;

import '../models/flavor_config.dart';

/// A class that generates per-flavor xcconfig files for iOS.
///
/// Generates 3 xcconfig files for each flavor:
///   - Debug-{flavor}.xcconfig   — includes Pods-Runner.debug-{flavor}.xcconfig + Generated.xcconfig
///   - Release-{flavor}.xcconfig — includes Pods-Runner.release-{flavor}.xcconfig + Generated.xcconfig
///   - Profile-{flavor}.xcconfig — includes Pods-Runner.profile-{flavor}.xcconfig + Generated.xcconfig
///
/// Each file sets the APP_DISPLAY_NAME variable, which can be referenced
/// in Info.plist via $(APP_DISPLAY_NAME).
///
/// CocoaPods xcconfig includes use #include? (optional) so the project can
/// be opened in Xcode before `pod install` is run.
class XcconfigGenerator {
  /// Generates per-flavor xcconfig files in the specified [xcconfigDir] directory.
  static void generate(
    String xcconfigDir,
    String flavor,
    FlavorConfig config, {
    bool dryRun = false,
  }) {
    print('  · flavor=$flavor');
    final vars = _buildXcconfigVars(config, flavor: flavor);
    const podsBase = 'Pods/Target Support Files/Pods-Runner';

    // Debug xcconfig — CocoaPods flavor-specific debug config + Flutter Generated settings
    _writeXcconfig(
      p.join(xcconfigDir, 'Debug-$flavor.xcconfig'),
      '#include? "$podsBase/Pods-Runner.debug-$flavor.xcconfig"\n'
      '#include "Generated.xcconfig"\n'
      '$vars',
      dryRun: dryRun,
    );
    // Release xcconfig — CocoaPods flavor-specific release config + Flutter Generated settings
    _writeXcconfig(
      p.join(xcconfigDir, 'Release-$flavor.xcconfig'),
      '#include? "$podsBase/Pods-Runner.release-$flavor.xcconfig"\n'
      '#include "Generated.xcconfig"\n'
      '$vars',
      dryRun: dryRun,
    );
    // Profile xcconfig — CocoaPods flavor-specific profile config + Flutter Generated settings
    _writeXcconfig(
      p.join(xcconfigDir, 'Profile-$flavor.xcconfig'),
      '#include? "$podsBase/Pods-Runner.profile-$flavor.xcconfig"\n'
      '#include "Generated.xcconfig"\n'
      '$vars',
      dryRun: dryRun,
    );
  }

  /// Composes xcconfig variable strings from a FlavorConfig.
  ///
  /// APP_DISPLAY_NAME: default app name (referenced via $(APP_DISPLAY_NAME) in Info.plist)
  /// If [flavor] is provided and [config.appIcon] is set,
  /// ASSETCATALOG_COMPILER_APPICON_NAME is automatically set to AppIcon-{flavor}.
  static String _buildXcconfigVars(FlavorConfig config, {String? flavor}) {
    final sb = StringBuffer();
    sb.writeln('APP_DISPLAY_NAME=${config.name}');

    final ios = config.ios;
    if (ios != null) {
      if (ios.teamId != null) {
        sb.writeln('DEVELOPMENT_TEAM=${ios.teamId}');
      }
      if (ios.codeSignIdentity != null) {
        sb.writeln('CODE_SIGN_IDENTITY=${ios.codeSignIdentity}');
      }
      if (ios.provisioningProfile != null) {
        sb.writeln('PROVISIONING_PROFILE_SPECIFIER=${ios.provisioningProfile}');
      }
      if (ios.entitlements != null) {
        sb.writeln('CODE_SIGN_ENTITLEMENTS=${ios.entitlements}');
      }
    }
    if (config.appIcon != null && flavor != null) {
      sb.writeln('ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon-$flavor');
    }
    return sb.toString();
  }

  /// Deletes unused per-flavor xcconfig files from [xcconfigDir].
  ///
  /// [activeFlavors]: list of currently active flavors (only their xcconfigs are preserved)
  /// Only targets files matching the Debug-{flavor}, Release-{flavor}, Profile-{flavor} pattern.
  /// Deletes xcconfig files not generated by easy_setup.
  /// Only Generated.xcconfig is preserved (generated by flutter pub get).
  static void cleanupUnusedXcconfigs(
    String xcconfigDir,
    Set<String> activeFlavors, {
    bool dryRun = false,
  }) {
    final dir = Directory(xcconfigDir);
    if (!dir.existsSync()) return;

    // List of flavor xcconfig filenames that easy_setup will generate
    final activeFiles = <String>{};
    for (final flavor in activeFlavors) {
      activeFiles.add('Debug-$flavor.xcconfig');
      activeFiles.add('Release-$flavor.xcconfig');
      activeFiles.add('Profile-$flavor.xcconfig');
    }

    // Only preserve Generated.xcconfig (generated by flutter pub get)
    const preserveFiles = {'Generated.xcconfig'};

    try {
      for (final entity in dir.listSync()) {
        if (entity is! File) continue;
        final fileName = p.basename(entity.path);
        if (!fileName.endsWith('.xcconfig')) continue;

        if (preserveFiles.contains(fileName)) continue;
        if (activeFiles.contains(fileName)) continue;

        if (dryRun) {
          print('  · [dry-run] Would delete: ${p.basename(entity.path)}');
        } else {
          entity.deleteSync();
          print('  · deleted: ${p.basename(entity.path)}');
        }
      }
    } catch (e) {
      print('  ⚠ cleanup failed: $e');
    }
  }

  /// Writes an individual xcconfig file (overwrites if it already exists).
  static void _writeXcconfig(
    String path,
    String content, {
    required bool dryRun,
  }) {
    if (dryRun) {
      print('  · [dry-run] $path');
      return;
    }
    final file = File(path);
    file.parent.createSync(recursive: true);
    file.writeAsStringSync(content);
    print('  ✓ ${p.basename(path)}');
  }
}
