/// Starter design sources for the marketing screenshot renderer.
///
/// Everything here is written once and then owned by the project — the
/// `store-screenshots` skill (or the user) restyles `template.html` and
/// fills `screenshots.yaml`; easy_setup only ever re-renders them.
abstract final class ScreenshotTemplates {
  /// Default portrait template. Sized entirely off `{{W}}`/`{{H}}` so the
  /// same file renders the iPhone, iPad and Play canvases.
  static String screenshot() => '''
<!doctype html>
<!-- Store screenshot template — generated by easy_setup, yours to redesign.
     Placeholders: {{W}} {{H}} {{IMG}} {{SCREEN_AR}} {{INDEX}} {{COUNT}}
     {{LOCALE}} {{DEVICE}} {{SCREEN}} {{FONT_CSS}} {{FONT_FAMILIES}},
     every text field from screenshots.yaml as {{TITLE}}, {{SUBTITLE}}, ...
     and every palette entry as {{C_BG}}, {{C_ACCENT}}, ... -->
<html lang="{{LOCALE}}">
<head>
<meta charset="utf-8">
<style>
{{FONT_CSS}}

:root {
  /* One vertical and one horizontal unit, so a design tuned on the
     iPhone canvas still holds on the iPad and Play canvases. */
  --u: calc({{H}}px / 100);
  --w: calc({{W}}px / 100);
}

* { margin: 0; padding: 0; box-sizing: border-box; }

html, body { width: {{W}}px; height: {{H}}px; overflow: hidden; }

body {
  background: {{C_BG}};
  color: {{C_TITLE}};
  font-family: {{FONT_FAMILIES}} -apple-system, BlinkMacSystemFont,
    'Helvetica Neue', 'Segoe UI', system-ui, sans-serif;
  display: flex;
  flex-direction: column;
  align-items: center;
  -webkit-font-smoothing: antialiased;
}

.copy {
  text-align: center;
  padding: calc(var(--u) * 6) calc(var(--w) * 9) 0;
  width: 100%;
}
.copy > *:empty { display: none; }

.eyebrow {
  font-size: calc(var(--u) * 1.05);
  letter-spacing: calc(var(--u) * 0.28);
  text-transform: uppercase;
  color: {{C_ACCENT}};
  margin-bottom: calc(var(--u) * 1.6);
}

h1 {
  font-size: calc(var(--u) * 2.5);
  font-weight: 700;
  line-height: 1.3;
  letter-spacing: -0.02em;
  word-break: keep-all;
}

.subtitle {
  font-size: calc(var(--u) * 1.35);
  line-height: 1.55;
  margin-top: calc(var(--u) * 1.8);
  color: {{C_SUBTITLE}};
  word-break: keep-all;
}

/* The device bleeds off the bottom edge — the top of the screen is what
   sells the app, and the store crops nothing. */
.stage {
  flex: 1;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  overflow: hidden;
  margin-top: calc(var(--u) * 4.5);
}

.device {
  width: 80%;
  padding: calc(var(--w) * 1.1);
  background: {{C_BEZEL}};
  border-radius: calc(var(--w) * 7);
  box-shadow: 0 calc(var(--u) * 1.2) calc(var(--u) * 3.5) rgba(0, 0, 0, 0.45);
}

.device img {
  display: block;
  width: 100%;
  border-radius: calc(var(--w) * 6);
}
</style>
</head>
<body>
  <div class="copy">
    <div class="eyebrow">{{EYEBROW}}</div>
    <h1>{{TITLE}}</h1>
    <div class="subtitle">{{SUBTITLE}}</div>
  </div>
  <div class="stage">
    <div class="device"><img src="{{IMG}}" alt=""></div>
  </div>
</body>
</html>
''';

  /// Google Play feature graphic — 1024×500, no device, `{{IMG}}` is the
  /// app icon rather than a capture.
  static String featureGraphic() => '''
<!doctype html>
<!-- Play feature graphic (1024x500) — generated by easy_setup.
     Copy comes from the `feature_graphic` entry in screenshots.yaml.
     Play crops the edges on some surfaces: keep content off the margins. -->
<html lang="{{LOCALE}}">
<head>
<meta charset="utf-8">
<style>
{{FONT_CSS}}
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body { width: {{W}}px; height: {{H}}px; overflow: hidden; }
body {
  background: {{C_BG}};
  color: {{C_TITLE}};
  font-family: {{FONT_FAMILIES}} -apple-system, BlinkMacSystemFont,
    'Helvetica Neue', 'Segoe UI', system-ui, sans-serif;
  display: flex;
  align-items: center;
  gap: 44px;
  padding: 0 92px;
  -webkit-font-smoothing: antialiased;
}
img { width: 148px; height: 148px; border-radius: 33px; flex: none; }
img[src=""] { display: none; }
.text > *:empty { display: none; }
h1 { font-size: 58px; font-weight: 700; letter-spacing: -0.02em; }
.subtitle {
  font-size: 26px;
  margin-top: 14px;
  color: {{C_SUBTITLE}};
}
</style>
</head>
<body>
  <img src="{{IMG}}" alt="">
  <div class="text">
    <h1>{{TITLE}}</h1>
    <div class="subtitle">{{SUBTITLE}}</div>
  </div>
</body>
</html>
''';

  /// Starter `screenshots.yaml`. Renders correctly as-is; the copy is what
  /// the user (or the skill) fills in.
  static String design(String appName) => '''
# Store screenshot copy and palettes — generated by easy_setup.
#
# Screen ids match the raw capture filenames:
#   assets/store/screenshots/raw/<locale>/<device>/01_home.png  ->  01_home
# Files render in filename order, which is the order the stores display
# them, so keep the numeric prefixes.
#
# Every palette entry becomes a {{C_<KEY>}} placeholder in template.html
# and every text field a {{<KEY>}} one — add your own freely. Keys must be
# plain identifiers (letters, digits, underscore).
#
# Copy is plain text: it is HTML-escaped, so markup here does nothing.
# A "\\n" in a title becomes a line break.

# Font family -> project-relative file. Embedded into the render, so the
# output is identical on every machine. Leave empty to use system fonts.
fonts: {}
#  Display: assets/fonts/Pretendard-Bold.ttf

defaults:
  palette: default
  # Pixels trimmed off the bottom of every capture (an ad banner, a
  # simulator home indicator, ...). Override per screen when needed.
  crop_bottom: 0
  text:
    # Shown above the headline on every screen unless a screen overrides it.
    en-US:
      eyebrow: $appName

palettes:
  default:
    bg: 'linear-gradient(180deg, #1b2338 0%, #0b0e16 100%)'
    title: '#ffffff'
    subtitle: '#9aa3bd'
    accent: '#7c8cff'
    bezel: '#05070d'

screens: {}
#  01_home:
#    palette: default
#    crop_bottom: 0
#    text:
#      en-US:
#        title: "One line that sells the app"
#        subtitle: "A short supporting sentence."

# Optional Google Play feature graphic (1024x500), rendered from
# feature_graphic.html. Delete this entry to skip it.
#  feature_graphic:
#    text:
#      en-US:
#        title: $appName
#        subtitle: "Your tagline"
''';

  /// The Claude Code skill that drives the pipeline.
  static String skill({
    required String projectRoot,
    required String assetsDir,
    required String bundleId,
    required List<String> devices,
  }) =>
      '''
---
name: store-screenshots
description: Create App Store and Google Play marketing screenshots —
  capture app screens, write the per-screen copy, design the frame
  template, and render exact store sizes. Use when asked for store
  screenshots, 스토어 스크린샷, or after UI changes that need a refreshed set.
---

# Store screenshots

Two layers. You own layer ②; `easy_setup setup --only screenshots`
renders it.

```
${projectRoot == '.' ? '' : '$projectRoot/'}$assetsDir/
  raw/<locale>/<device>/01_home.png   ① raw captures (inputs)
  screenshots.yaml                    ② copy + palettes
  template.html                       ② the frame design
  feature_graphic.html                ② Play feature graphic (1024x500)
->  fastlane/screenshots/<locale>/            iOS, uploaded by deliver
->  fastlane/metadata/android/<locale>/images/ Play, uploaded by supply
```

Devices configured in easy_setup.yaml: ${devices.join(', ')}.

## 1. Capture the raw screens

`simctl` cannot tap the UI, so this part is collaborative: ask the user to
bring each screen up in the Simulator, then capture it.

```sh
# Freeze the status bar so every shot matches (Apple expects this).
xcrun simctl status_bar booted override --time "9:41" \\
  --dataNetwork wifi --wifiMode active --wifiBars 3 \\
  --cellularMode active --cellularBars 4 \\
  --batteryState charged --batteryLevel 100
xcrun simctl launch booted $bundleId

xcrun simctl io booted screenshot \\
  $assetsDir/raw/<locale>/<device>/01_home.png
```

- Number the files in display order — `01_`, `02_`, ... Apple shows at
  most 10, Google Play needs at least 2 phone shots.
- Clear transient UI first: no open swipe actions, no edit mode, no
  keyboard, no debug banner.
- Ad banners and other bottom chrome are removed with `crop_bottom` in
  screenshots.yaml (pixels trimmed from the raw image), not by editing
  the PNG.
- A different locale means relaunching the app in that locale and
  capturing into that locale's folder.

## 2. Write the copy

Edit `$assetsDir/screenshots.yaml`. Per screen and locale:

- `title` — one benefit, not a feature name. Two lines maximum; use `\\n`
  for the break. This is the single most important text in the listing.
- `subtitle` — one supporting sentence, optional.
- `eyebrow` — usually the app name; set once under `defaults.text`.

Copy is **plain text**: it is HTML-escaped before it reaches the page, so
`&` and `<` render as themselves and markup in the YAML does not work.
`\\n` is the one exception — it becomes a line break. Styling belongs in
template.html, never in the copy. A field left out renders empty rather
than as its `{{TOKEN}}`, so an optional subtitle is fine.

Pull the product language from `easy_setup_store_info.yaml` (the store
name, subtitle and description) so the screenshots and the listing agree.

## 3. Design the frame

Edit `$assetsDir/template.html`. It is a plain HTML page rendered at the
exact store size — no build step, no framework, no network access.

- **Match the brand.** Take the palette from `site/style.css` if the promo
  site exists, otherwise from the app icon. Put the colors in the
  `palettes:` block, never hardcoded in the HTML: they become `{{C_BG}}`,
  `{{C_ACCENT}}`, ... and can then vary per screen.
- **Size everything off `var(--u)` / `var(--w)`** (1% of the canvas height
  and width). The same template must render 1320x2868, 2064x2752 and
  1080x1920 — fixed pixel sizes only look right on one of them.
- **Bundle the fonts.** List them under `fonts:` with a project-relative
  path; they are embedded as data URIs. Do not link Google Fonts — the
  renderer has no network and would silently fall back.
- **No external resources at all.** No CDN, no remote images.

## 4. Render and verify

```sh
easy_setup setup --only screenshots
```

Then **Read at least one rendered PNG per device** and look at it:

- Is the headline fully visible, not clipped or overflowing?
- Did the intended font render, or did it fall back?
- Is the bottom chrome (ad banner, home indicator) gone?
- Does it look like the app, or like a generic template?

Iterate on screenshots.yaml / template.html and re-render. The raw
captures never need to change.
''';
}
