/// Starter design sources for the marketing screenshot renderer.
///
/// Everything here is written once and then owned by the project — the
/// `store-screenshots` skill (or the user) restyles `template.html` and
/// fills `screenshots.yaml`; easy_setup only ever re-renders them.
abstract final class ScreenshotTemplates {
  /// Default portrait template. Sized entirely off `{{W}}`/`{{H}}` so the
  /// same file renders the iPhone, iPad and Play canvases.
  static String screenshot() => '''
<!doctype html>
<!-- Store screenshot template — generated by easy_setup, yours to redesign.
     Placeholder names, written in double braces. Built in: W, H, IMG,
     SCREEN_AR, INDEX, COUNT, LOCALE, DEVICE, SCREEN, FONT_CSS,
     FONT_FAMILIES. Every text field in screenshots.yaml becomes one
     (TITLE, SUBTITLE, ...) and every palette entry becomes C_ plus its
     key (C_BG, C_TITLE, ...). Names are listed without braces here so
     this comment cannot itself be mistaken for a placeholder. -->
<html lang="{{LOCALE}}">
<head>
<meta charset="utf-8">
<style>
{{FONT_CSS}}

:root {
  /* One vertical and one horizontal unit, so a design tuned on the
     iPhone canvas still holds on the iPad and Play canvases. */
  --u: calc({{H}}px / 100);
  --w: calc({{W}}px / 100);
}

* { margin: 0; padding: 0; box-sizing: border-box; }

html, body { width: {{W}}px; height: {{H}}px; overflow: hidden; }

body {
  background: {{C_BG}};
  color: {{C_TITLE}};
  font-family: {{FONT_FAMILIES}} -apple-system, BlinkMacSystemFont,
    'Helvetica Neue', 'Segoe UI', system-ui, sans-serif;
  display: flex;
  flex-direction: column;
  align-items: center;
  -webkit-font-smoothing: antialiased;
}

.copy {
  text-align: center;
  padding: calc(var(--u) * 6) calc(var(--w) * 9) 0;
  width: 100%;
}
/* Only the text collapses when a field is unset — a decorative
   element is empty by design and must survive. */
.copy h1:empty, .copy .subtitle:empty { display: none; }

h1 {
  font-size: calc(var(--u) * 2.5);
  font-weight: 700;
  line-height: 1.3;
  letter-spacing: -0.02em;
  word-break: keep-all;
}

.subtitle {
  font-size: calc(var(--u) * 1.35);
  line-height: 1.55;
  margin-top: calc(var(--u) * 1.8);
  color: {{C_SUBTITLE}};
  word-break: keep-all;
}

/* The device bleeds off the bottom edge — the top of the screen is what
   sells the app, and the store crops nothing. */
.stage {
  flex: 1;
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: flex-start;
  overflow: hidden;
  margin-top: calc(var(--u) * 4.5);
}

.device {
  /* Wide enough that the device is always taller than the space left for
     it, on every canvas and however long the headline runs. That is what
     makes the bleed above actually happen instead of leaving dead
     background under a floating phone. Drop below ~84% and short copy
     starts letting the whole device fit. */
  width: 86%;
  padding: calc(var(--w) * 1.1);
  background: {{C_BEZEL}};
  border-radius: calc(var(--w) * 7);
  box-shadow: 0 calc(var(--u) * 1) calc(var(--u) * 3) rgba(0, 0, 0, 0.18);
}

.device img {
  display: block;
  width: 100%;
  border-radius: calc(var(--w) * 6);
}
</style>
</head>
<body>
  <div class="copy">
    <h1>{{TITLE}}</h1>
    <div class="subtitle">{{SUBTITLE}}</div>
  </div>
  <div class="stage">
    <div class="device"><img src="{{IMG}}" alt=""></div>
  </div>
</body>
</html>
''';

  /// Google Play feature graphic — 1024×500, no device, `{{IMG}}` is the
  /// app icon rather than a capture.
  static String featureGraphic() => '''
<!doctype html>
<!-- Play feature graphic (1024x500) — generated by easy_setup.
     Copy comes from the `feature_graphic` entry in screenshots.yaml.
     Play crops the edges on some surfaces: keep content off the margins. -->
<html lang="{{LOCALE}}">
<head>
<meta charset="utf-8">
<style>
{{FONT_CSS}}
* { margin: 0; padding: 0; box-sizing: border-box; }
html, body { width: {{W}}px; height: {{H}}px; overflow: hidden; }
body {
  background: {{C_BG}};
  color: {{C_TITLE}};
  font-family: {{FONT_FAMILIES}} -apple-system, BlinkMacSystemFont,
    'Helvetica Neue', 'Segoe UI', system-ui, sans-serif;
  display: flex;
  align-items: center;
  gap: 44px;
  padding: 0 92px;
  -webkit-font-smoothing: antialiased;
}
img { width: 148px; height: 148px; border-radius: 33px; flex: none; }
img[src=""] { display: none; }
.text h1:empty, .text .subtitle:empty { display: none; }
h1 { font-size: 58px; font-weight: 700; letter-spacing: -0.02em; }
.subtitle {
  font-size: 26px;
  margin-top: 14px;
  color: {{C_SUBTITLE}};
}
</style>
</head>
<body>
  <img src="{{IMG}}" alt="">
  <div class="text">
    <h1>{{TITLE}}</h1>
    <div class="subtitle">{{SUBTITLE}}</div>
  </div>
</body>
</html>
''';

  /// Starter `screenshots.yaml`. Renders correctly as-is; the copy is what
  /// the user (or the skill) fills in.
  static String design(String appName) => '''
# Store screenshot copy and palettes — generated by easy_setup.
#
# Screen ids match the raw capture filenames:
#   assets/store/screenshots/raw/<locale>/<device>/01_home.png  ->  01_home
# Files render in filename order, which is the order the stores display
# them, so keep the numeric prefixes.
#
# Every palette entry becomes a {{C_<KEY>}} placeholder in template.html
# and every text field a {{<KEY>}} one — add your own freely. Keys must be
# plain identifiers (letters, digits, underscore).
#
# Copy is plain text: it is HTML-escaped, so markup here does nothing.
# A "\\n" in a title becomes a line break.

# Font family -> project-relative file. Embedded into the render, so the
# output is identical on every machine. Leave empty to use system fonts.
fonts: {}
#  Display: assets/fonts/Pretendard-Bold.ttf

defaults:
  palette: default
  # Pixels trimmed off the bottom of every capture (an ad banner, a
  # simulator home indicator, ...). Override per screen when needed.
  crop_bottom: 0
  # Copy shared by every screen, per locale. Only needed for a field you
  # added to template.html that repeats — title and subtitle belong under
  # each screen instead.
  # text:
  #   en-US: { tagline: Your one-liner }

palettes:
  # Light by default: most apps are dark, and a dark page would swallow
  # the device. Recolour freely — these are just the starting values.
  default:
    bg: '#ffffff'
    title: '#111318'
    subtitle: '#5f6570'
    bezel: '#1b1c1e'

screens: {}
#  01_home:
#    palette: default
#    crop_bottom: 0
#    text:
#      en-US:
#        title: "One line that sells the app"
#        subtitle: "A short supporting sentence."

# Optional Google Play feature graphic (1024x500), rendered from
# feature_graphic.html. Delete this entry to skip it.
#  feature_graphic:
#    text:
#      en-US:
#        title: $appName
#        subtitle: "Your tagline"
''';

  /// The Claude Code skill that drives the pipeline.
  static String skill({
    required String projectRoot,
    required String assetsDir,
    required String bundleId,
    required List<String> devices,
  }) =>
      '''
---
name: store-screenshots
description: Create App Store and Google Play marketing screenshots —
  capture app screens, write the per-screen copy, design the frame
  template, and render exact store sizes. Use when asked for store
  screenshots, 스토어 스크린샷, or after UI changes that need a refreshed set.
---

# Store screenshots

Two layers: ① the raw captures and ② the marketing frame around them. You
write the tour that produces ① and the design that produces ②; easy_setup
runs both.

```
${projectRoot == '.' ? '' : '$projectRoot/'}$assetsDir/
  raw/<locale>/<device>/01_home.png   ① captures, from the tour
  screenshots.yaml                    ② copy + palettes
  template.html                       ② the frame design
  feature_graphic.html                ② Play feature graphic (1024x500)

integration_test/store_screenshots_test.dart   ① the tour — you write it
integration_test/store_screenshot_harness.dart ① generated, do not edit

->  fastlane/screenshots/<locale>/            iOS, uploaded by deliver
->  fastlane/metadata/android/<locale>/images/ Play, uploaded by supply
```

Devices configured in easy_setup.yaml: ${devices.join(', ')}.

## 1. Write the tour, then capture

`easy_setup capture` boots the simulator, freezes the status bar and runs
`integration_test/store_screenshots_test.dart` — **you write that tour**.
It is the one part of the pipeline that cannot be generic: only this app
knows which screens sell it and what data they need.

Read `integration_test/store_screenshot_harness.dart` first (generated,
do not edit). It gives you:

- `shot(tester, '01_home')` — asks the host to capture. The name is the
  file name, which is also the order the stores display them in, so keep
  `01_`, `02_`, ... Apple shows at most 10, Play needs at least 2.
- `pumpFor(tester, duration)` — **use this, never `pumpAndSettle`.** An
  app with a looping animation never settles, and the test hangs forever.
- `waitFor(tester, finder)` — for screens that load asynchronously.
- `captureLocale` — the locale being captured, for locale-specific data.

Writing the tour:

- **Seed demo data before pumping the widget**, so the first frame is
  already populated. An empty app makes empty screenshots. Use real
  sentences, realistic dates, and enough rows that lists and charts look
  alive — this is the app's shop window.
- **Drive the app's own state or `Navigator` directly** instead of
  tapping through the UI. `nav.push(MaterialPageRoute(...))` or a state
  method is far less brittle than hunting for a widget by text, and a
  screenshot tour does not need to prove the taps work.
- Clear transient UI: no open swipe actions, no edit mode, no keyboard.
- Give each screen a beat (`pumpFor`) before shooting so animations and
  images have landed.

```sh
easy_setup capture                          # every configured locale x device
easy_setup capture --locale ko --device iphone_6_9
```

Captures land in `$assetsDir/raw/<locale>/<device>/`. Ad banners and other
bottom chrome are removed with `crop_bottom` in screenshots.yaml (pixels
trimmed at render time), not by editing the PNG.

If a screen genuinely cannot be reached from a test, capture that one by
hand into the same folder — the renderer does not care where a raw PNG
came from. Ask the user to bring the screen up, then:

```sh
xcrun simctl launch booted $bundleId
xcrun simctl io booted screenshot \\
  $assetsDir/raw/<locale>/<device>/09_manual.png
```

## 2. Write the copy

`easy_setup capture` already added an entry per captured screen to
`$assetsDir/screenshots.yaml`, with the fields commented out. Uncomment
and fill them.

**Read each raw PNG before writing its line.** The copy has to describe
the screen it sits above — a headline about search over a screenshot of
the settings page is worse than no headline. Look at what is actually on
screen, then write for it.

Per screen and locale:

- `title` — one benefit, not a feature name. Two lines maximum; use `\\n`
  for the break. This is the single most important text in the listing.
- `subtitle` — one supporting sentence, optional.

Copy is **plain text**: it is HTML-escaped before it reaches the page, so
`&` and `<` render as themselves and markup in the YAML does not work.
`\\n` is the one exception — it becomes a line break. Styling belongs in
template.html, never in the copy. A field left out renders empty rather
than as its `{{TOKEN}}`, so an optional subtitle is fine.

Pull the product language from `easy_setup_store_info.yaml` (the store
name, subtitle and description) so the screenshots and the listing agree.

## 3. Design the frame

Edit `$assetsDir/template.html`. It is a plain HTML page rendered at the
exact store size — no build step, no framework, no network access.

- **Match the brand.** Take the palette from `site/style.css` if the promo
  site exists, otherwise from the app icon. Put the colors in the
  `palettes:` block, never hardcoded in the HTML: they become `{{C_BG}}`,
  `{{C_ACCENT}}`, ... and can then vary per screen.
- **Size everything off `var(--u)` / `var(--w)`** (1% of the canvas height
  and width). The same template must render 1320x2868, 2064x2752 and
  1080x1920 — fixed pixel sizes only look right on one of them.
- **Bundle the fonts.** List them under `fonts:` with a project-relative
  path; they are embedded as data URIs. Do not link Google Fonts — the
  renderer has no network and would silently fall back.
- **No external resources at all.** No CDN, no remote images.

## 4. Render and verify

```sh
easy_setup capture                    # only when the tour changed
easy_setup setup --only screenshots   # frame them
```

Then **Read at least one rendered PNG per device** and look at it:

- Is the headline fully visible, not clipped or overflowing?
- Did the intended font render, or did it fall back?
- Is the bottom chrome (ad banner, home indicator) gone?
- Does it look like the app, or like a generic template?

Iterate on screenshots.yaml / template.html and re-render. The raw
captures never need to change.
''';
}
