/// Starter templates for the promo site (V2_PLAN §5 store assets).
///
/// Deliberately plain and easy to rewrite: one small stylesheet driven by
/// CSS custom properties, three semantic pages. The AI skill (or the user)
/// restyles them; easy_setup never overwrites a page it did not just
/// create.
abstract final class SiteTemplates {
  /// Escapes a value for an HTML text node or a double-quoted attribute.
  /// Everything interpolated into the templates comes from user YAML, so
  /// it is escaped without exception.
  static String esc(String value) => value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');

  /// Returns [url] when it is a safe http(s)/mailto link, else null —
  /// keeps `javascript:` and friends out of generated href attributes.
  static String? safeUrl(String? url) {
    if (url == null) return null;
    final trimmed = url.trim();
    final lower = trimmed.toLowerCase();
    if (lower.startsWith('http://') ||
        lower.startsWith('https://') ||
        lower.startsWith('mailto:') ||
        // Relative links inside the site.
        (!lower.contains(':') && !lower.startsWith('//'))) {
      return esc(trimmed);
    }
    return null;
  }

  static String stylesheet() => '''
/* Generated by easy_setup — restyle freely, this file is yours.
   Every color/shape knob lives here so a redesign rarely touches HTML. */
:root {
  --bg: #f7f7f5;
  --panel: #ffffff;
  --ink: #1b1c1e;
  --ink-dim: #6b6f76;
  --line: #e3e3df;
  --accent: #3b5bdb;
  --radius: 14px;
  --maxw: 720px;
}

@media (prefers-color-scheme: dark) {
  :root {
    --bg: #14161a;
    --panel: #1c1f24;
    --ink: #f2f3f5;
    --ink-dim: #a2a8b3;
    --line: #2a2e35;
    --accent: #91a7ff;
  }
}

* { margin: 0; padding: 0; box-sizing: border-box; }

body {
  background: var(--bg);
  color: var(--ink);
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui,
    sans-serif;
  line-height: 1.7;
  padding: 40px 20px 72px;
  -webkit-font-smoothing: antialiased;
}

.wrap { max-width: var(--maxw); margin: 0 auto; }

.site-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 40px;
}
.site-header img { width: 44px; height: 44px; border-radius: 10px; }
.site-header .name { font-weight: 600; }
.site-header nav { margin-left: auto; display: flex; gap: 16px; }

a { color: var(--accent); }
nav a { color: var(--ink-dim); text-decoration: none; font-size: 14px; }
nav a:hover { color: var(--ink); }

.hero { text-align: center; padding: 24px 0 40px; }
.hero .app-icon {
  width: 96px; height: 96px; border-radius: 22px; margin-bottom: 20px;
}
.hero h1 { font-size: 32px; line-height: 1.35; letter-spacing: -0.02em; }
.hero .tagline { color: var(--ink-dim); margin-top: 12px; }

.panel {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: var(--radius);
  padding: 24px;
  margin: 24px 0;
}

.feature { display: flex; gap: 12px; padding: 10px 0; }
.feature .dot { color: var(--accent); }

.store-cta {
  display: inline-block;
  background: var(--accent);
  color: #fff;
  text-decoration: none;
  padding: 12px 22px;
  border-radius: 999px;
  font-weight: 600;
}

h1 { font-size: 26px; letter-spacing: -0.02em; }
h2 { font-size: 18px; margin: 28px 0 8px; }
.dim { color: var(--ink-dim); }
ul { padding-left: 20px; }
li { margin: 4px 0; }

.footer {
  margin-top: 48px;
  padding-top: 20px;
  border-top: 1px solid var(--line);
  color: var(--ink-dim);
  font-size: 14px;
  text-align: center;
}
''';

  static String index({
    required String appName,
    required String tagline,
    required String description,
    required List<String> features,
    required String contactEmail,
    required String locale,
    String? appStoreUrl,
    String? playStoreUrl,
  }) {
    final featureItems = features
        .map((feature) =>
            '      <div class="feature"><span class="dot">◆</span>'
            '<p>${esc(feature)}</p></div>')
        .join('\n');
    final appStore = safeUrl(appStoreUrl);
    final playStore = safeUrl(playStoreUrl);
    final stores = [
      if (appStore != null)
        '      <a class="store-cta" href="$appStore">App Store</a>',
      if (playStore != null)
        '      <a class="store-cta" href="$playStore">Google Play</a>',
    ].join('\n');
    return '''
<!doctype html>
<html lang="${esc(locale)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(appName)}</title>
<meta name="description" content="${esc(tagline)}">
<link rel="icon" href="icon.png">
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrap">
${_header(appName, current: 'index')}
  <section class="hero">
    <img class="app-icon" src="icon.png" alt="${esc(appName)}">
    <h1>${esc(appName)}</h1>
    <p class="tagline">${esc(tagline)}</p>
  </section>

  <section class="panel">
$featureItems
  </section>

  <p class="dim">${esc(description)}</p>

${stores.isEmpty ? '' : '  <p style="text-align:center;margin:32px 0">\n$stores\n  </p>\n'}
${_footer(contactEmail)}
</div>
</body>
</html>
''';
  }

  static String support({
    required String appName,
    required String contactEmail,
    required String locale,
  }) =>
      '''
<!doctype html>
<html lang="${esc(locale)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Support — ${esc(appName)}</title>
<link rel="icon" href="icon.png">
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrap">
${_header(appName, current: 'support')}
  <h1>Support</h1>
  <p class="dim">Questions or trouble? Get in touch any time.</p>

  <div class="panel">
    <p><strong>Email</strong> —
      <a href="mailto:${esc(contactEmail)}">${esc(contactEmail)}</a></p>
    <p class="dim">We usually reply within 2-3 days. Including your device
      model and OS version helps us solve things much faster.</p>
  </div>

  <h2>Frequently asked questions</h2>
  <p class="dim">TODO: replace with real questions from your users.</p>

${_footer(contactEmail)}
</div>
</body>
</html>
''';

  static String privacy({
    required String appName,
    required String contactEmail,
    required String locale,
    required String effectiveDate,
  }) =>
      '''
<!doctype html>
<html lang="${esc(locale)}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy Policy — ${esc(appName)}</title>
<link rel="icon" href="icon.png">
<link rel="stylesheet" href="style.css">
</head>
<body>
<div class="wrap">
${_header(appName, current: 'privacy')}
  <h1>Privacy Policy</h1>
  <p class="dim">Effective date: ${esc(effectiveDate)}</p>

  <div class="panel">
    <p><strong>Review this document before publishing.</strong> It is a
      starting point generated by easy_setup, not legal advice — it must
      match what your app actually does and the App Privacy answers you
      give in App Store Connect / Play Console.</p>
  </div>

  <h2>What we collect</h2>
  <p>TODO: list every category your app collects, or state that the app
    collects nothing. Keep this consistent with your store privacy
    labels.</p>

  <h2>How it is used</h2>
  <p>TODO: describe the purpose of each category (app functionality,
    analytics, advertising, ...).</p>

  <h2>Third parties</h2>
  <p>TODO: name the SDKs that receive data (e.g. Firebase Analytics,
    Sentry, AdMob) and link their policies.</p>

  <h2>Data retention and deletion</h2>
  <p>TODO: how long data is kept and how a user can request deletion.</p>

  <h2>Children</h2>
  <p>TODO: state your policy for users under 13 (or the local
    equivalent).</p>

  <h2>Contact</h2>
  <p>Questions about this policy:
    <a href="mailto:${esc(contactEmail)}">${esc(contactEmail)}</a></p>

${_footer(contactEmail)}
</div>
</body>
</html>
''';

  static String _header(String appName, {required String current}) {
    final links = [
      if (current != 'index') '      <a href="index.html">Home</a>',
      if (current != 'support') '      <a href="support.html">Support</a>',
      if (current != 'privacy') '      <a href="privacy.html">Privacy</a>',
    ].join('\n');
    return '''
  <header class="site-header">
    <img src="icon.png" alt="${esc(appName)}">
    <span class="name">${esc(appName)}</span>
    <nav>
$links
    </nav>
  </header>
''';
  }

  static String _footer(String contactEmail) => '''
  <footer class="footer">
    <p><a href="mailto:${esc(contactEmail)}">${esc(contactEmail)}</a></p>
    <p><a href="privacy.html">Privacy</a> · <a href="support.html">Support</a></p>
  </footer>
''';

  /// GitHub Actions workflow publishing [siteDir] to Pages.
  static String pagesWorkflow(String siteDir) => '''
# Generated by easy_setup. Publishes the promo site to GitHub Pages.
# Enable once at: repo Settings > Pages > Source: GitHub Actions
name: Publish site

on:
  push:
    branches: [main]
    paths: ['$siteDir/**', '.github/workflows/pages.yml']
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: \${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: '$siteDir'
      - id: deployment
        uses: actions/deploy-pages@v4
''';
}
